# Certify that a marked flag is a LOCAL datum attached to a place, not a
# global object.  In the Fano-plane collineation group PSL(3,2) the 21
# involutions correspond bijectively to the 21 point-line flags; each is
# a transvection with cycle type 1^3 2^2 whose fixed set is its axis and
# whose invariant lines are the three lines through its center -- the
# axis plus two "mixed" lines, each the center together with one
# transposed pair.  Every place of the septic splitting field whose
# decomposition group is generated by such an involution therefore
# carries its own canonical flag.  The published quartic Paley tripod is
# the axis at the archimedean place.

SizeScreen([100000,100000]);;

gA := (1,2)(3,4)(7,8)(9,10)(13,14)(15,16)(19,20)(21,22);;
gB := (1,16,11,3)(2,9,21,12)(4,5,8,23)(6,22,14,18)(13,20)(15,17);;
G := Group(gA,gB);;
x := (3,21)(4,16)(9,22)(10,15)(11,20)(12,19)(13,18)(14,17);;
r := (3,18)(4,16)(5,6)(7,23)(10,14)(12,19)(13,21)(15,17);;

C := Centralizer(G,x);;
H := Filtered([1..23],point -> point^x=point);;
pointAction := ActionHomomorphism(C,H,OnPoints);;
PA := Image(pointAction);;

lines := Set(List(
    Filtered(AsList(PA),element -> Order(element)=2),
    element -> Set(Filtered([1..7],point -> point^element=point))
));;
sheetLines := List(lines,line -> Set(List(line,i -> H[i])));;
involutions := Filtered(AsList(PA),element -> Order(element)=2);;

FlagOf := function(element)
    local axis,invariant;
    axis := Set(Filtered([1..7],point -> point^element=point));
    invariant := Filtered(lines,line -> OnSets(line,element)=line);
    return [Intersection(invariant)[1],Position(lines,axis)];
end;;

flags := List(involutions,FlagOf);;
allFlags := Set(Concatenation(List([1..7],lineIndex ->
    List(lines[lineIndex],point -> [point,lineIndex]))));;

if Size(G)<>10200960
        or Size(PA)<>168
        or StructureDescription(PA)<>"PSL(3,2)"
        or Length(lines)<>7
        or Length(involutions)<>21
        or Length(allFlags)<>21
        or Length(Set(flags))<>21
        or Set(flags)<>allFlags then
    Error("flag-involution bijection changed");
fi;

# transitivity on flags and the flag stabilizer
flagOrbit := Orbit(PA,flags[1],
    function(flag,element)
        return [flag[1]^element,
            Position(lines,OnSets(lines[flag[2]],element))];
    end);;
flagStabilizer := Stabilizer(PA,flags[1],
    function(flag,element)
        return [flag[1]^element,
            Position(lines,OnSets(lines[flag[2]],element))];
    end);;

if Length(flagOrbit)<>21 or Size(flagStabilizer)<>8 then
    Error("flag action changed");
fi;

# the local structure of every transvection
for involution in involutions do
    flag := FlagOf(involution);
    axis := lines[flag[2]];
    fixedPoints := Set(Filtered([1..7],point -> point^involution=point));
    transposedPairs := Filtered(
        Orbits(Group(involution),[1..7]),orbit -> Length(orbit)=2);
    invariantLines := Filtered(lines,line ->
        OnSets(line,involution)=line);
    mixedLines := Filtered(invariantLines,line -> line<>axis);
    if SortedList(List(Orbits(Group(involution),[1..7]),Length))
                <>[1,1,1,2,2]
            or fixedPoints<>axis
            or Length(transposedPairs)<>2
            or Length(invariantLines)<>3
            or not ForAll(invariantLines,line -> flag[1] in line)
            or Length(mixedLines)<>2
            or Set(List(mixedLines,line ->
                Difference(line,[flag[1]])))
                <>Set(List(transposedPairs,Set))
            or Size(Centralizer(PA,involution))<>8 then
        Error("transvection local structure changed");
    fi;
od;

# place counts for the septic splitting field
splittingDegree := Size(PA);;
archimedeanPlaces := splittingDegree/2;;
placesPerFlag := archimedeanPlaces/21;;
if splittingDegree<>168
        or archimedeanPlaces<>84
        or placesPerFlag<>4
        or placesPerFlag<>Size(Centralizer(PA,involutions[1]))/2 then
    Error("place count changed");
fi;

# the archimedean instance
realImage := Image(pointAction,r);;
realFlag := FlagOf(realImage);;
realAxisSheets := Set(List(lines[realFlag[2]],i -> H[i]));;
realCenterSheet := H[realFlag[1]];;

if not r in C
        or Order(realImage)<>2
        or realAxisSheets<>[1,2,8]
        or realCenterSheet<>8 then
    Error("archimedean flag changed");
fi;

output := OutputTextFile("results/local_flag_places_group_summary.txt",
    false);;
SetPrintFormattingStatus(output,false);;
AppendTo(output,
    "schema=m23.miraculous-fixed-point.local-flag-places-group.v1\n",
    "collineation_group=PSL(3,2)\n",
    "involutions=21\n",
    "flags=21\n",
    "involution_flag_map_bijective=true\n",
    "flag_action_transitive=true\n",
    "flag_stabilizer_order=8\n",
    "transvection_cycle_type_on_sheets=1^3_2^2\n",
    "transvection_fixed_set_equals_axis=true\n",
    "transvection_invariant_lines=3\n",
    "invariant_lines_all_contain_center=true\n",
    "mixed_lines=2\n",
    "mixed_line_minus_center_equals_a_transposed_pair=true\n",
    "involution_centralizer_order=8\n",
    "septic_splitting_degree=168\n",
    "archimedean_places=84\n",
    "places_per_flag=4\n",
    "archimedean_flag_center_sheet=",realCenterSheet,"\n",
    "archimedean_flag_axis_sheets=",realAxisSheets,"\n",
    "published_tripod_is_the_archimedean_axis=true\n",
    "flag_is_a_local_datum_not_a_global_subscheme=true\n"
);;
CloseStream(output);;

Print("21 involutions <-> 21 flags bijectively; transitive, stabilizer 8\n");
Print("each transvection: type 1^3 2^2, axis = fixed set, ",
    "2 mixed lines = center + a transposed pair\n");
Print("84 archimedean places of the septic closure, 4 per flag\n");
Print("archimedean flag = (",realCenterSheet,",",realAxisSheets,
    ") = the published tripod\n");

QUIT_GAP(0);
